services:
  app:
    build:
      context: docker/nginx
    ports:
        - "800:80"
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    tty: true
    restart: unless-stopped

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    restart: unless-stopped
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    build:
      context: docker/php-cli
    tty: true
    volumes:
      - ./:/app

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "54322:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
