parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Shared\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    App\Shared\:
        resource: '../src/Shared'

    App\Article\:
        resource: '../src/Article/'
        exclude:
            - '../src/Article/Domain/Entity'
            - '../src/Article/Application/Command'
            - '../src/Article/Application/Query'

    App\User\:
        resource: '../src/User/'
        exclude:
            - '../src/User/Domain/Entity'
            - '../src/User/Application/Command'
            - '../src/User/Application/Query'
